AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

# Rails specific

require: rubocop-rails

Rails/OutputSafety:
  Enabled: false # This disallows .html_safe
Rails/TimeZone:
  Enabled: false # This enforces Time.zone.now
Rails/Date:
  Enabled: false # This enforces Time.zone.today
Rails/HasAndBelongsToMany:
  Enabled: false # This disallows HABTM.

# Project styling

Style: # Style is not Rubocop's responsibility. Use an auto-formatter like rufo.
  Enabled: false
Layout: # Layout is not Rubocop's responsibility. Use an auto-formatter like rufo.
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
    - "spec/**/*_spec.rb"
    - "config/**/*"
    - "spec/factories/*"
Lint/ShadowingOuterLocalVariable: # shadowing is a language feature - we should use it where appropriate.
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

# Concessions (remove these if possible / appropriate).

Bundler/OrderedGems:
  Enabled: false # we have a ton of gems, grouped arbitrarily. Could be tackled later.
Metrics/MethodLength:
  Max: 20 # default was 10.
Metrics/ClassLength:
  Max: 500 # default was 100.
Metrics/AbcSize:
  Max: 30 # default is 15.
